using UnityEngine;

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

namespace Rukhanka.Hybrid
{
public partial class RigDefinitionBaker
{
	public static readonly AvatarMaskBodyPart[] humanPartToAvatarMaskPartRemapTable = 
	{
		//	Hips = 0,
		AvatarMaskBodyPart.Root,
		//	LeftUpperLeg = 1,
		AvatarMaskBodyPart.LeftLeg,
		//	RightUpperLeg = 2,
		AvatarMaskBodyPart.RightLeg,
		//	LeftLowerLeg = 3,
		AvatarMaskBodyPart.LeftLeg,
		//	RightLowerLeg = 4,
		AvatarMaskBodyPart.RightLeg,
		//	LeftFoot = 5,
		AvatarMaskBodyPart.LeftLeg,
		//	RightFoot = 6,
		AvatarMaskBodyPart.RightLeg,
		//	Spine = 7,
		AvatarMaskBodyPart.Body,
		//	Chest = 8,
		AvatarMaskBodyPart.Body,
		//	Neck = 9,
		AvatarMaskBodyPart.Head,
		//	Head = 10,
		AvatarMaskBodyPart.Head,
		//	LeftShoulder = 11,
		AvatarMaskBodyPart.LeftArm,
		//	RightShoulder = 12,
		AvatarMaskBodyPart.RightArm,
		//	LeftUpperArm = 13,
		AvatarMaskBodyPart.LeftArm,
		//	RightUpperArm = 14,
		AvatarMaskBodyPart.RightArm,
		//	LeftLowerArm = 15,
		AvatarMaskBodyPart.LeftArm,
		//	RightLowerArm = 16,
		AvatarMaskBodyPart.RightArm,
		//	LeftHand = 17,
		AvatarMaskBodyPart.LeftArm,
		//	RightHand = 18,
		AvatarMaskBodyPart.RightArm,
		//	LeftToes = 19,
		AvatarMaskBodyPart.LeftLeg,
		//	RightToes = 20,
		AvatarMaskBodyPart.RightLeg,
		//	LeftEye = 21,
		AvatarMaskBodyPart.Head,
		//	RightEye = 22,
		AvatarMaskBodyPart.Head,
		//	Jaw = 23,
		AvatarMaskBodyPart.Head,
		//	LeftThumbProximal = 24,
		AvatarMaskBodyPart.LeftFingers,
		//	LeftThumbIntermediate = 25,
		AvatarMaskBodyPart.LeftFingers,
		//	LeftThumbDistal = 26,
		AvatarMaskBodyPart.LeftFingers,
		//	LeftIndexProximal = 27,
		AvatarMaskBodyPart.LeftFingers,
		//	LeftIndexIntermediate = 28,
		AvatarMaskBodyPart.LeftFingers,
		//	LeftIndexDistal = 29,
		AvatarMaskBodyPart.LeftFingers,
		//	LeftMiddleProximal = 30,
		AvatarMaskBodyPart.LeftFingers,
		//	LeftMiddleIntermediate = 31,
		AvatarMaskBodyPart.LeftFingers,
		//	LeftMiddleDistal = 32,
		AvatarMaskBodyPart.LeftFingers,
		//	LeftRingProximal = 33,
		AvatarMaskBodyPart.LeftFingers,
		//	LeftRingIntermediate = 34,
		AvatarMaskBodyPart.LeftFingers,
		//	LeftRingDistal = 35,
		AvatarMaskBodyPart.LeftFingers,
		//	LeftLittleProximal = 36,
		AvatarMaskBodyPart.LeftFingers,
		//	LeftLittleIntermediate = 37,
		AvatarMaskBodyPart.LeftFingers,
		//	LeftLittleDistal = 38,
		AvatarMaskBodyPart.LeftFingers,
		//	RightThumbProximal = 39,
		AvatarMaskBodyPart.RightFingers,
		//	RightThumbIntermediate = 40,
		AvatarMaskBodyPart.RightFingers,
		//	RightThumbDistal = 41,
		AvatarMaskBodyPart.RightFingers,
		//	RightIndexProximal = 42,
		AvatarMaskBodyPart.RightFingers,
		//	RightIndexIntermediate = 43,
		AvatarMaskBodyPart.RightFingers,
		//	RightIndexDistal = 44,
		AvatarMaskBodyPart.RightFingers,
		//	RightMiddleProximal = 45,
		AvatarMaskBodyPart.RightFingers,
		//	RightMiddleIntermediate = 46,
		AvatarMaskBodyPart.RightFingers,
		//	RightMiddleDistal = 47,
		AvatarMaskBodyPart.RightFingers,
		//	RightRingProximal = 48,
		AvatarMaskBodyPart.RightFingers,
		//	RightRingIntermediate = 49,
		AvatarMaskBodyPart.RightFingers,
		//	RightRingDistal = 50,
		AvatarMaskBodyPart.RightFingers,
		//	RightLittleProximal = 51,
		AvatarMaskBodyPart.RightFingers,
		//	RightLittleIntermediate = 52,
		AvatarMaskBodyPart.RightFingers,
		//	RightLittleDistal = 53,
		AvatarMaskBodyPart.RightFingers,
		//	UpperChest = 54,
		AvatarMaskBodyPart.Body,
	};
}
}
